# This configuration is used for Okta authentication

CGIDScriptTimeout 100

LoadModule auth_openidc_module /lib/apache2/modules/mod_auth_openidc.so

# === OIDC settings ===
OIDCProviderMetadataURL            https://sanger.okta.com/.well-known/openid-configuration
OIDCClientID                       ${OIDCClientID}
OIDCClientSecret                   ${OIDCClientSecret}
OIDCRedirectURI                    https://${NPG_TRACKING_SERVER_NAME}:${NPG_TRACKING_SERVER_SSL_PORT}/cgi-bin/okta-callback.cgi
OIDCCryptoPassphrase               ${OIDCClientSecret}
OIDCScope                          "openid email profile"
OIDCPassClaimsAs                   environment
OIDCRefreshAccessTokenBeforeExpiry 0
OIDCAuthRequestParams              prompt=login

<Location /perl/protected>
        Options    +ExecCGI
        AddHandler cgi-script .cgi .pl
        AuthType   openid-connect
        Require    valid-user
</Location>

<Location /perl/okta-callback.cgi>
        Options    +ExecCGI
        AddHandler cgi-script .cgi .pl
        AuthType   openid-connect
        Require    all granted
        PassEnv    OIDCClientID
        PassEnv    OIDCClientSecret
        SetEnv     OIDCRedirectURI https://${NPG_TRACKING_SERVER_NAME}:${NPG_TRACKING_SERVER_SSL_PORT}/cgi-bin/okta-callback.cgi
</Location>
