# This configuration is used for Okta authentication

CGIDScriptTimeout 100

LoadModule auth_openidc_module /lib/apache2/modules/mod_auth_openidc.so

# === OIDC settings ===
OIDCProviderMetadataURL            https://sanger.okta.com/.well-known/openid-configuration
OIDCClientID                       ${OIDCClientID}
OIDCClientSecret                   ${OIDCClientSecret}
OIDCRedirectURI                    https://${NPG_TRACKING_SERVER_NAME}:${NPG_TRACKING_SERVER_SSL_PORT}/perl/protected/dummy-page
OIDCCryptoPassphrase               ${OIDCClientSecret}
OIDCScope                          "openid email profile"
OIDCPassClaimsAs                   environment
OIDCPassIDTokenAs                  serialized
OIDCRefreshAccessTokenBeforeExpiry 0
OIDCAuthRequestParams              prompt=login

<Location /perl/protected>
    AuthType              openid-connect
    Require               valid-user
</Location>
