# This configuration is used for Okta authentication

CGIDScriptTimeout 100

LoadModule auth_openidc_module /lib/apache2/modules/mod_auth_openidc.so

ScriptAlias "/perl/"  "${NPG_TRACKING_SERVER_PATH}/cgi-bin/"
<Directory "${NPG_TRACKING_SERVER_PATH}/cgi-bin/">
    Options +ExecCGI
    AddHandler cgi-script .pl .cgi
    AllowOverride None
    Require all granted
    AcceptPathInfo On
</Directory>

# === OIDC settings ===
OIDCProviderMetadataURL            ${OIDCProviderMetadataURL}
OIDCRedirectURI                    /callback
OIDCClientID                       ${OIDCClientID}
OIDCClientSecret                   ${OIDCClientSecret}
OIDCCryptoPassphrase               ${OIDCCryptoPassphrase}
OIDCScope                          "openid email profile"
OIDCRemoteUserClaim                preferred_username
OIDCPassClaimsAs                   environment
OIDCSSLValidateServer              On

# Session duration
OIDCSessionInactivityTimeout       1800
OIDCSessionMaxDuration             28800

# Cookie settings
OIDCCookie                         ${OIDCCookieName}

# Unset header
RequestHeader unset OIDC_CLAIM_sub
RequestHeader unset OIDC_CLAIM_email
RequestHeader unset OIDC_CLAIM_name
RequestHeader unset OIDC_CLAIM_preferred_username
RequestHeader unset OIDC_CLAIM_groups
RequestHeader unset OIDC_access_token
RequestHeader unset OIDC_id_token

<Location />
    AuthType openid-connect
    Require valid-user
    OIDCUnAuthAction pass
</Location>

<Location /callback>
    AuthType openid-connect
    Require valid-user
</Location>

<LocationMatch "^/perl/oidc_auth\.cgi$">
    AuthType openid-connect
    Require valid-user
    OIDCUnAuthAction auth
</LocationMatch>
